# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
swagger/components/responses/404.yaml:
  struct:
    - '#/content'
swagger/components/responses/401.yaml:
  struct:
    - '#/content'
