openapi: 3.1.0
info:
  version: 1.0.0
  title: ContactApp
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    ContactApp is an application for managing contacts.
    It provides CRUD functionality and user authentication via JWT and Google OAuth.
tags:
  - name: Contacts
    description: Endpoints for managing contacts.
  - name: Auth
    description: Endpoints for user authentication and authorization.
servers:
  - url: http://localhost:3001
  # - url: #посилання на задеплоєний сайт
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml
  /auth/send-reset-email:
    post:
      $ref: ../swagger/paths/auth/send-reset-email.yaml
  /auth/reset-pwd:
    post:
      $ref: ../swagger/paths/auth/reset-pwd.yaml
  /auth/get-oauth-url:
    get:
      $ref: ../swagger/paths/auth/get-oauth-url.yaml
  /auth/confirm-oauth:
    post:
      $ref: ../swagger/paths/auth/confirm-oauth.yaml
components:
  schemas:
    Contact:
      $ref: ../swagger/components/schemas/contact.yaml
    User:
      $ref: ../swagger/components/schemas/user.yaml
    Session:
      $ref: ../swagger/components/schemas/session.yaml
  responses:
    BadRequest:
      $ref: ../swagger/components/responses/400.yaml
    Unauthorized:
      $ref: ../swagger/components/responses/401.yaml
    NotFound:
      $ref: ../swagger/components/responses/404.yaml
    InternalServerError:
      $ref: ../swagger/components/responses/500.yaml
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
